WITH CTE AS
(
SELECT O_CUSTKEY, L_DISCOUNT,L_EXTENDEDPRICE,(L_EXTENDEDPRICE* (1 - L_DISCOUNT)) AS REV
FROM {{ source('oracle', 'orders') }} O
JOIN {{ source('oracle', 'lineitem') }} L ON O.O_ORDERKEY = L.L_ORDERKEY
),
CTE2 AS
(
SELECT O_CUSTKEY, SUM(REV) AS REVENUE
FROM CTE
GROUP BY O_CUSTKEY
)
SELECT O_CUSTKEY, REVENUE
FROM CTE2
QUALIFY DENSE_RANK() OVER (ORDER BY CTE2.REVENUE DESC)<=5
