
WITH CTE AS
(
SELECT C.C_CUSTKEY,L.L_EXTENDEDPRICE,L.L_DISCOUNT,N.N_NATIONKEY,N.N_NAME
FROM {{source ('oracle', 'customer')}} C
JOIN {{ source('oracle', 'nation') }} N ON C.C_NATIONKEY = N.N_NATIONKEY
JOIN {{ source('oracle', 'orders') }} O ON C.C_CUSTKEY = O.O_CUSTKEY
JOIN {{ source('oracle', 'lineitem') }} L ON L.L_ORDERKEY= O.O_ORDERKEY
),

CTE2 AS
(
SELECT CTE.N_NAME, CTE.C_CUSTKEY, SUM(L_EXTENDEDPRICE* (1 - L_DISCOUNT)) AS REVENUE
FROM CTE
GROUP BY CTE.N_NAME, CTE.C_CUSTKEY
ORDER BY REVENUE DESC
)
SELECT *,
ROW_NUMBER() OVER (PARTITION BY CTE2.N_NAME ORDER BY REVENUE DESC) AS R_N
FROM CTE2
QUALIFY R_N = 1 OR R_N =2 OR R_N =3
