WITH CTE AS
(
SELECT O_CUSTKEY,COUNT(*) AS NO_OF_ORDERS
FROM {{ source('oracle', 'orders') }}
GROUP BY O_CUSTKEY
ORDER BY NO_OF_ORDERS DESC
)
SELECT *, 
RANK() OVER (ORDER BY NO_OF_ORDERS DESC) AS RNK,
DENSE_RANK() OVER (ORDER BY NO_OF_ORDERS DESC) AS D_RNK
FROM CTE
QUALIFY D_RNK =2